const rules: { [key: string]: any[] } = {

    // #region Possible problems
    "array-callback-return": ['error'],
    "constructor-super": ['error'],
    "for-direction": ['error'],
    "getter-return": ['error'],
    "no-async-promise-executor": ['error'],
    "no-await-in-loop": ['error'],
    "no-class-assign": ['error'],
    "no-compare-neg-zero": ['error'],
    "no-cond-assign": ['error'],
    "no-const-assign": ['error'],
    "no-constant-binary-expression": ['error'],
    "no-constant-condition": ['error'],
    "no-constructor-return": ['error'],
    "no-control-regex": ['error'],
    "no-debugger": ['warn'],
    "no-dupe-args": ['error'],
    "no-dupe-class-members": ['error'],
    "no-dupe-else-if": ['error'],
    "no-dupe-keys": ['error'],
    "no-duplicate-case": ['error'],
    "no-duplicate-imports": ['error'],
    "no-empty-character-class": ['error'],
    "no-empty-pattern": ['error'],
    "no-ex-assign": ['error'],
    "no-fallthrough": ['error', { 'allowEmptyCase': true }],
    "no-func-assign": ['error'],
    "no-import-assign": ['error'],
    "no-inner-declarations": ['error', 'both'],
    "no-invalid-regexp": ['error'],
    "no-irregular-whitespace": ['error', { 'skipStrings': true, 'skipComments': true, 'skipJSXText': true }],
    "no-loss-of-precision": ['error'],
    "no-misleading-character-class": ['error'],
    "no-new-native-nonconstructor": ['error'],
    "no-obj-calls": ['error'],
    "no-promise-executor-return": ['error'],
    "no-prototype-builtins": ['error'],
    "no-self-assign": ['error'],
    "no-self-compare": ['error'],
    "no-setter-return": ['error'],
    "no-sparse-arrays": ['error'],
    "no-template-curly-in-string": ['error'],
    "no-this-before-super": ['error'],
    "no-unassigned-vars": ['error'],
    "no-undef": ['error', { 'typeof': true }],
    "no-unexpected-multiline": ['error'],
    "no-unmodified-loop-condition": ['off'],
    "no-unreachable": ['error'],
    "no-unreachable-loop": ['error'],
    "no-unsafe-finally": ['error'],
    "no-unsafe-negation": ['error'],
    "no-unsafe-optional-chaining": ['error'],
    "no-unused-private-class-members": ['error'],
    "no-unused-vars": ['error', { 'args': 'all' }],
    "no-use-before-define": ['error'],
    "no-useless-assignment": ['error'],
    "no-useless-backreference": ['error'],
    "require-atomic-updates": ['error'],
    "use-isnan": ['error'],
    "valid-typeof": ['error'],
    // #endregion Possible problems

    // #region Suggestions
    "accessor-pairs": ['error'],
    // #endregion Suggestions
}

export default rules;
