const tsRules = {
    // Overrides of js/recommended
    'no-debugger': 'warn',
    'no-fallthrough': ['error', { allowEmptyCase: true }],
    'no-inner-declarations': ['error', 'both'],
    'no-irregular-whitespace': ['error', { skipStrings: true, skipComments: true, skipJSXText: true }],
    'no-undef': 'off', // TypeScript handles this; avoids false positives for DOM/TS types
    'no-unused-vars': 'off', // TypeScript handles this; avoids false positives for TS types

    // Possible problems (not in recommended)
    'array-callback-return': 'error',
    'no-await-in-loop': 'error',
    'no-duplicate-imports': 'error',
    'no-promise-executor-return': 'error',
    'no-self-compare': 'error',
    'no-template-curly-in-string': 'error',
    'no-unreachable-loop': 'error',
    'no-unused-private-class-members': 'error',
    'no-use-before-define': 'error',
    'no-useless-assignment': 'error',

    // Suggestions (not in recommended)
    'accessor-pairs': 'error',
    'block-scoped-var': 'error',
    'camelcase': ['error', { properties: 'always' }],
    'curly': 'error',
    'default-case': 'error',
    'default-case-last': 'error',
    'default-param-last': 'error',
    'dot-notation': 'error',
    'eqeqeq': 'error',
    'grouped-accessor-pairs': ['error', 'getBeforeSet'],
    'new-cap': ['error', { newIsCap: true }],
    'no-alert': 'warn',
    'no-caller': 'error',
    'no-empty-function': ['error', { allow: ['getters', 'setters', 'overrideMethods'] }],
    'no-empty-static-block': 'error',
    'no-eq-null': 'error',
    'no-eval': 'error',
    'no-extra-label': 'error',
    'no-implicit-globals': 'error',
    'no-implied-eval': 'error',
    'no-invalid-this': 'error',
    'no-iterator': 'error',
    'no-label-var': 'error',
    'no-labels': 'error',
    'no-lone-blocks': 'error',
    'no-lonely-if': 'error',
    'no-multi-assign': 'error',
    'no-multi-str': 'error',
    'no-negated-condition': 'error',
    'no-nested-ternary': 'error',
    'no-new': 'error',
    'no-new-func': 'error',
    'no-new-wrappers': 'error',
    'no-octal-escape': 'error',
    'no-param-reassign': ['error', { props: false }],
    'no-proto': 'error',
    'no-return-assign': ['error', 'always'],
    'no-script-url': 'error',
    'no-sequences': 'error',
    'no-throw-literal': 'error',
    'no-unneeded-ternary': 'error',
    'no-unused-expressions': 'error',
    'no-useless-call': 'error',
    'no-useless-computed-key': 'error',
    'no-useless-concat': 'error',
    'no-useless-constructor': 'error',
    'no-useless-rename': 'error',
    'no-useless-return': 'error',
    'no-var': 'error',
    'no-void': 'error',
    'prefer-const': 'error',
    'prefer-object-has-own': 'error',
    'prefer-object-spread': 'error',
    'prefer-spread': 'error',
    'prefer-template': 'error',
    'radix': ['error', 'as-needed'],
    'require-await': 'error',
    'yoda': 'error',

    // @typescript-eslint
    '@typescript-eslint/no-explicit-any': 'warn',
    '@typescript-eslint/no-unused-vars': ['error', { args: 'all', argsIgnorePattern: '^_', varsIgnorePattern: '^_' }],
    '@typescript-eslint/no-shadow': ['error', { hoist: 'all' }],
    '@typescript-eslint/consistent-type-imports': ['error', { prefer: 'type-imports', fixStyle: 'inline-type-imports' }]
};

export default tsRules;
